package org.sdato.geocell.testsupport

import org.h2.jdbcx.JdbcDataSource
import org.locationtech.jts.geom.Coordinate
import org.locationtech.jts.geom.Geometry
import org.locationtech.jts.geom.GeometryFactory
import org.locationtech.jts.geom.PrecisionModel
import org.locationtech.jts.io.WKTReader
import org.locationtech.jts.io.WKTWriter
import org.sdato.geocell.controller.cell.CellController
import org.sdato.geocell.repository.cell.CellRepository
import org.sdato.geocell.repository.cell.JdbcCellRepository
import org.sdato.geocell.service.cell.CellPolygonGenerator
import org.sdato.geocell.service.cell.CellService
import org.sdato.geocell.validator.CellUpsertRequestValidator
import org.springframework.jdbc.core.JdbcTemplate
import javax.sql.DataSource
import java.util.UUID
import kotlin.math.atan2
import kotlin.math.cos
import kotlin.math.pow
import kotlin.math.sin
import kotlin.math.sqrt

object H2GeoCellTestDatabase {
	private val geometryFactory = GeometryFactory(PrecisionModel(), 4326)
	private val wktReader = WKTReader(geometryFactory)
	private val wktWriter = WKTWriter()

	data class Environment(
		val dataSource: DataSource,
		val jdbcTemplate: JdbcTemplate,
		val repository: CellRepository,
		val service: CellService,
		val controller: CellController
	)

	fun create(): Environment {
		val dbName = "geocell_${UUID.randomUUID().toString().replace("-", "")}"
		val dataSource = JdbcDataSource().apply {
			setURL("jdbc:h2:mem:$dbName;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;DB_CLOSE_DELAY=-1")
			user = "sa"
			password = ""
		}
		val jdbcTemplate = JdbcTemplate(dataSource)
		registerSpatialFunctions(jdbcTemplate)
		createSchema(jdbcTemplate)
		seedData(jdbcTemplate)

		val repository = JdbcCellRepository(jdbcTemplate)
		val service = CellService(repository, CellUpsertRequestValidator(), CellPolygonGenerator())
		val controller = CellController(service)
		return Environment(dataSource, jdbcTemplate, repository, service, controller)
	}

	private fun registerSpatialFunctions(jdbcTemplate: JdbcTemplate) {
		listOf(
			"CREATE DOMAIN IF NOT EXISTS geography AS geometry",
			"CREATE ALIAS IF NOT EXISTS ST_MakePoint FOR \"org.sdato.geocell.testsupport.H2GeoCellSpatialFunctions.stMakePoint\"",
			"CREATE ALIAS IF NOT EXISTS ST_SetSRID FOR \"org.sdato.geocell.testsupport.H2GeoCellSpatialFunctions.stSetSrid\"",
			"CREATE ALIAS IF NOT EXISTS ST_X FOR \"org.sdato.geocell.testsupport.H2GeoCellSpatialFunctions.stX\"",
			"CREATE ALIAS IF NOT EXISTS ST_Y FOR \"org.sdato.geocell.testsupport.H2GeoCellSpatialFunctions.stY\"",
			"CREATE ALIAS IF NOT EXISTS ST_DWithin FOR \"org.sdato.geocell.testsupport.H2GeoCellSpatialFunctions.stDWithin\"",
			"CREATE ALIAS IF NOT EXISTS ST_Distance FOR \"org.sdato.geocell.testsupport.H2GeoCellSpatialFunctions.stDistance\"",
			"CREATE ALIAS IF NOT EXISTS ST_MakeEnvelope FOR \"org.sdato.geocell.testsupport.H2GeoCellSpatialFunctions.stMakeEnvelope\"",
			"CREATE ALIAS IF NOT EXISTS ST_Within FOR \"org.sdato.geocell.testsupport.H2GeoCellSpatialFunctions.stWithin\"",
			"CREATE ALIAS IF NOT EXISTS ST_Intersects FOR \"org.sdato.geocell.testsupport.H2GeoCellSpatialFunctions.stIntersects\"",
			"CREATE ALIAS IF NOT EXISTS ST_Equals FOR \"org.sdato.geocell.testsupport.H2GeoCellSpatialFunctions.stEquals\"",
			"CREATE ALIAS IF NOT EXISTS ST_GeogFromText FOR \"org.sdato.geocell.testsupport.H2GeoCellSpatialFunctions.stGeogFromText\"",
			"CREATE ALIAS IF NOT EXISTS ST_AsGeoJSON FOR \"org.sdato.geocell.testsupport.H2GeoCellSpatialFunctions.stAsGeoJson\"",
			"CREATE ALIAS IF NOT EXISTS ST_Collect FOR \"org.sdato.geocell.testsupport.H2GeoCellSpatialFunctions.stCollect\"",
			"CREATE ALIAS IF NOT EXISTS ST_ConcaveHull FOR \"org.sdato.geocell.testsupport.H2GeoCellSpatialFunctions.stConcaveHull\""
		).forEach(jdbcTemplate::execute)
	}

	private fun createSchema(jdbcTemplate: JdbcTemplate) {
		listOf(
			"""
			CREATE TABLE country (
				name VARCHAR(100) PRIMARY KEY,
				code VARCHAR(4),
				polygon GEOMETRY,
				flag VARCHAR(100)
			)
			""".trimIndent(),
			"""
			CREATE TABLE district (
				id VARCHAR(20) PRIMARY KEY,
				district VARCHAR(100) NOT NULL,
				polygon GEOMETRY,
				country_id VARCHAR(100) NOT NULL
			)
			""".trimIndent(),
			"""
			CREATE TABLE county (
				id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				id_county VARCHAR(20) NOT NULL,
				county VARCHAR(100) NOT NULL,
				polygon GEOMETRY,
				district_id VARCHAR(20)
			)
			""".trimIndent(),
			"""
			CREATE TABLE location (
				id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				coordinates GEOMETRY,
				address VARCHAR(100),
				address1 VARCHAR(100),
				zip4 INTEGER NOT NULL,
				zip3 INTEGER NOT NULL,
				postal_designation VARCHAR(100),
				id_county_id BIGINT
			)
			""".trimIndent(),
			"""
			CREATE TABLE mccmnc (
				id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				type VARCHAR(100),
				mcc INTEGER NOT NULL,
				mnc INTEGER NOT NULL,
				brand VARCHAR(100),
				"operator" VARCHAR(200),
				status VARCHAR(100),
				bands VARCHAR(200),
				notes VARCHAR(300),
				country_id VARCHAR(100)
			)
			""".trimIndent(),
			"""
			CREATE TABLE enbgnb (
				id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				enb_gnb INTEGER NOT NULL,
				location_id BIGINT NOT NULL
			)
			""".trimIndent(),
			"""
			CREATE TABLE band (
				id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				band VARCHAR(50),
				bandwidth DOUBLE PRECISION,
				uplink_freq DOUBLE PRECISION,
				downlink_freq DOUBLE PRECISION,
				earfcn DOUBLE PRECISION
			)
			""".trimIndent(),
			"""
			CREATE TABLE cell (
				id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				lac_tac VARCHAR(50),
				ci VARCHAR(20),
				eci_nci VARCHAR(20),
				cgi VARCHAR(30),
				paragon_cgi VARCHAR(100),
				technology INTEGER NOT NULL,
				azimuth INTEGER NOT NULL,
				name VARCHAR(200),
				created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
				updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
				band_id BIGINT,
				enb_gnb_id BIGINT,
				location_id BIGINT,
				mcc_mnc_id BIGINT,
				updated_by BIGINT,
				created_by BIGINT
			)
			""".trimIndent(),
			"""
			CREATE TABLE cell_polygon (
				id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				polygon GEOMETRY,
				cell_id BIGINT,
				polygon_short GEOMETRY
			)
			""".trimIndent(),
			"""
			CREATE TABLE caop_23p (
				ogc_fid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				wkb_geometry GEOMETRY NOT NULL,
				fid INTEGER NOT NULL,
				dicofre VARCHAR(6) NOT NULL,
				area_ha DOUBLE PRECISION NOT NULL,
				des_simpli VARCHAR(255) NOT NULL,
				layer TEXT NOT NULL,
				path TEXT,
				freguesia TEXT NOT NULL,
				concelho TEXT NOT NULL,
				concelho_cd TEXT NOT NULL,
				distrito TEXT NOT NULL,
				distrito_cd TEXT NOT NULL
			)
			""".trimIndent()
		).forEach(jdbcTemplate::execute)
	}

	private fun seedData(jdbcTemplate: JdbcTemplate) {
		jdbcTemplate.update(
			"INSERT INTO country (name, code) VALUES (?, ?)",
			"Portugal",
			"PT"
		)
		jdbcTemplate.update(
			"INSERT INTO district (id, district, country_id) VALUES (?, ?, ?)",
			"11",
			"Lisboa",
			"Portugal"
		)
		jdbcTemplate.update(
			"INSERT INTO district (id, district, country_id) VALUES (?, ?, ?)",
			"01",
			"Aveiro",
			"Portugal"
		)
		jdbcTemplate.update(
			"INSERT INTO county (id_county, county, district_id) VALUES (?, ?, ?)",
			"01",
			"Oeiras",
			"11"
		)
		jdbcTemplate.update(
			"INSERT INTO county (id_county, county, district_id) VALUES (?, ?, ?)",
			"02",
			"Amadora",
			"11"
		)
		jdbcTemplate.update(
			"INSERT INTO county (id_county, county, district_id) VALUES (?, ?, ?)",
			"01",
			"Aveiro",
			"01"
		)

		jdbcTemplate.update(
			"INSERT INTO mccmnc (type, mcc, mnc, brand, \"operator\", status, bands, notes, country_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
			"mobile",
			268,
			3,
			"Vodafone",
			"Vodafone Portugal",
			"active",
			"800,1800",
			"seed",
			"Portugal"
		)
		jdbcTemplate.update(
			"INSERT INTO band (band, bandwidth, uplink_freq, downlink_freq, earfcn) VALUES (?, ?, ?, ?, ?)",
			"800",
			10.0,
			900.0,
			950.0,
			300
		)
		jdbcTemplate.update(
			"INSERT INTO band (band, bandwidth, uplink_freq, downlink_freq, earfcn) VALUES (?, ?, ?, ?, ?)",
			"700",
			10.0,
			800.0,
			850.0,
			200
		)

		jdbcTemplate.update(
			"INSERT INTO location (coordinates, address, address1, zip4, zip3, postal_designation, id_county_id) VALUES (ST_SetSRID(ST_MakePoint(?, ?), 4326), ?, ?, ?, ?, ?, ?)",
			-9.15,
			38.72,
			"Rua A",
			null,
			1000,
			100,
			"Oeiras",
			1L
		)
		jdbcTemplate.update(
			"INSERT INTO location (coordinates, address, address1, zip4, zip3, postal_designation, id_county_id) VALUES (ST_SetSRID(ST_MakePoint(?, ?), 4326), ?, ?, ?, ?, ?, ?)",
			-9.14,
			38.73,
			"Rua B",
			null,
			1001,
			101,
			"Oeiras",
			1L
		)
		jdbcTemplate.update(
			"INSERT INTO location (coordinates, address, address1, zip4, zip3, postal_designation, id_county_id) VALUES (ST_SetSRID(ST_MakePoint(?, ?), 4326), ?, ?, ?, ?, ?, ?)",
			-9.20,
			38.80,
			"Rua C",
			null,
			1002,
			102,
			"Amadora",
			2L
		)
		jdbcTemplate.update(
			"INSERT INTO location (coordinates, address, address1, zip4, zip3, postal_designation, id_county_id) VALUES (ST_SetSRID(ST_MakePoint(?, ?), 4326), ?, ?, ?, ?, ?, ?)",
			-8.65,
			40.64,
			"Rua D",
			null,
			1003,
			103,
			"Aveiro",
			3L
		)

		jdbcTemplate.update(
			"INSERT INTO enbgnb (enb_gnb, location_id) VALUES (?, ?)",
			1001,
			1L
		)
		jdbcTemplate.update(
			"INSERT INTO enbgnb (enb_gnb, location_id) VALUES (?, ?)",
			1002,
			4L
		)

		jdbcTemplate.update(
			"""
			INSERT INTO cell (
				lac_tac, ci, eci_nci, cgi, paragon_cgi, technology, azimuth, name,
				band_id, enb_gnb_id, location_id, mcc_mnc_id, updated_by, created_by, created_at, updated_at
			) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
			""".trimIndent(),
			"1234",
			"ci-1",
			"eci-1",
			"268-3-10000",
			null,
			4,
			90,
			"Cell 1",
			1L,
			1L,
			1L,
			1L,
			1L,
			1L
		)
		jdbcTemplate.update(
			"""
			INSERT INTO cell (
				lac_tac, ci, eci_nci, cgi, paragon_cgi, technology, azimuth, name,
				band_id, enb_gnb_id, location_id, mcc_mnc_id, updated_by, created_by, created_at, updated_at
			) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
			""".trimIndent(),
			"1234",
			"ci-2",
			"eci-2",
			null,
			"268-3-10001",
			5,
			120,
			"Cell 2",
			2L,
			1L,
			2L,
			1L,
			1L,
			1L
		)
		jdbcTemplate.update(
			"""
			INSERT INTO cell (
				lac_tac, ci, eci_nci, cgi, paragon_cgi, technology, azimuth, name,
				band_id, enb_gnb_id, location_id, mcc_mnc_id, updated_by, created_by, created_at, updated_at
			) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
			""".trimIndent(),
			"9999",
			"ci-3",
			"eci-3",
			"268-3-20000",
			null,
			4,
			180,
			"Cell 3",
			1L,
			2L,
			3L,
			1L,
			1L,
			1L
		)
		jdbcTemplate.update(
			"""
			INSERT INTO cell (
				lac_tac, ci, eci_nci, cgi, paragon_cgi, technology, azimuth, name,
				band_id, enb_gnb_id, location_id, mcc_mnc_id, updated_by, created_by, created_at, updated_at
			) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
			""".trimIndent(),
			"1234",
			"ci-4",
			"eci-4",
			"268-3-30000",
			null,
			10,
			270,
			"Cell 4",
			1L,
			2L,
			4L,
			1L,
			1L,
			1L
		)

		jdbcTemplate.update(
			"INSERT INTO cell_polygon (polygon, cell_id, polygon_short) VALUES (ST_GeogFromText(?), ?, ST_GeogFromText(?))",
			"POLYGON(( -9.16 38.71, -9.13 38.71, -9.13 38.74, -9.16 38.74, -9.16 38.71 ))",
			1L,
			"POLYGON(( -9.16 38.71, -9.13 38.71, -9.13 38.74, -9.16 38.74, -9.16 38.71 ))"
		)
		jdbcTemplate.update(
			"INSERT INTO cell_polygon (polygon, cell_id, polygon_short) VALUES (ST_GeogFromText(?), ?, ST_GeogFromText(?))",
			"POLYGON(( -9.15 38.72, -9.12 38.72, -9.12 38.75, -9.15 38.75, -9.15 38.72 ))",
			2L,
			"POLYGON(( -9.15 38.72, -9.12 38.72, -9.12 38.75, -9.15 38.75, -9.15 38.72 ))"
		)

		jdbcTemplate.update(
			"INSERT INTO caop_23p (wkb_geometry, fid, dicofre, area_ha, des_simpli, layer, path, freguesia, concelho, concelho_cd, distrito, distrito_cd) VALUES (ST_GeogFromText(?), ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
			"POLYGON(( -9.18 38.70, -9.10 38.70, -9.10 38.76, -9.18 38.76, -9.18 38.70 ))",
			1,
			"1101",
			1000.0,
			"Oeiras",
			"layer",
			null,
			"Freguesia A",
			"Oeiras",
			"1101",
			"Lisboa",
			"11"
		)
		jdbcTemplate.update(
			"INSERT INTO caop_23p (wkb_geometry, fid, dicofre, area_ha, des_simpli, layer, path, freguesia, concelho, concelho_cd, distrito, distrito_cd) VALUES (ST_GeogFromText(?), ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
			"POLYGON(( -9.23 38.77, -9.17 38.77, -9.17 38.83, -9.23 38.83, -9.23 38.77 ))",
			2,
			1102,
			900.0,
			"Amadora",
			"layer",
			null,
			"Freguesia B",
			"Amadora",
			"1102",
			"Lisboa",
			"11"
		)
	}
}

object H2GeoCellSpatialFunctions {
	private val geometryFactory = GeometryFactory(PrecisionModel(), 4326)
	private val wktReader = WKTReader(geometryFactory)
	private val wktWriter = WKTWriter()

	@JvmStatic
	fun stMakePoint(x: Double, y: Double): Geometry =
		geometryFactory.createPoint(Coordinate(x, y))

	@JvmStatic
	fun stSetSrid(geometry: Geometry, srid: Int): Geometry = geometry

	@JvmStatic
	fun stX(geometry: Geometry): Double = geometry.coordinate.x

	@JvmStatic
	fun stY(geometry: Geometry): Double = geometry.coordinate.y

	@JvmStatic
	fun stDWithin(left: Geometry, right: Geometry, distanceMeters: Double): Boolean =
		stDistance(left, right) <= distanceMeters

	@JvmStatic
	fun stDistance(left: Geometry, right: Geometry): Double {
		val a = left.coordinate
		val b = right.coordinate
		val earthRadius = 6_371_000.0
		val lat1 = Math.toRadians(a.y)
		val lat2 = Math.toRadians(b.y)
		val deltaLat = Math.toRadians(b.y - a.y)
		val deltaLon = Math.toRadians(b.x - a.x)
		val h = sin(deltaLat / 2).pow(2) + cos(lat1) * cos(lat2) * sin(deltaLon / 2).pow(2)
		val c = 2 * atan2(sqrt(h), sqrt(1 - h))
		return earthRadius * c
	}

	@JvmStatic
	fun stMakeEnvelope(minLon: Double, minLat: Double, maxLon: Double, maxLat: Double, srid: Int): Geometry =
		geometryFactory.createPolygon(
			arrayOf(
				Coordinate(minLon, minLat),
				Coordinate(maxLon, minLat),
				Coordinate(maxLon, maxLat),
				Coordinate(minLon, maxLat),
				Coordinate(minLon, minLat)
			)
		)

	@JvmStatic
	fun stWithin(left: Geometry, right: Geometry): Boolean = left.within(right)

	@JvmStatic
	fun stIntersects(left: Geometry, right: Geometry): Boolean = left.intersects(right)

	@JvmStatic
	fun stGeogFromText(wkt: String): Geometry = wktReader.read(normalizeWkt(wkt))

	@JvmStatic
	fun stAsGeoJson(geometry: Geometry?): String? = geometry?.toGeoJson()

	@JvmStatic
	fun stCollect(geometry: Geometry): Geometry = geometry

	@JvmStatic
	fun stConcaveHull(geometry: Geometry, ratio: Double): Geometry = geometry.convexHull()

	@JvmStatic
	fun stEquals(left: Geometry, right: Geometry): Boolean = left.equalsTopo(right)

	private fun Geometry.toGeoJson(): String = when (geometryType.uppercase()) {
		"POINT" -> """{"type":"Point","coordinates":[${coordinate.x},${coordinate.y}]}"""
		"POLYGON" -> {
			val rings = (0 until numGeometries).joinToString(",") { index ->
				val geom = getGeometryN(index)
				val coords = geom.coordinates.joinToString(",") { "[${it.x},${it.y}]" }
				"[$coords]"
			}
			"""{"type":"Polygon","coordinates":[$rings]}"""
		}
		"GEOMETRYCOLLECTION" -> {
			val items = (0 until numGeometries).joinToString(",") { index ->
				getGeometryN(index).toGeoJson()
			}
			"""{"type":"GeometryCollection","geometries":[$items]}"""
		}
		else -> """{"type":"${geometryType}","wkt":"${wktWriter.write(this)}"}"""
	}

	private fun normalizeWkt(wkt: String): String {
		val withoutSrid = wkt.trim().removePrefix("SRID=4326;")
		val withoutZ = withoutSrid.replace(Regex("""\bZ\b"""), "")
		return withoutZ.replace(
			Regex("""(-?\d+(?:\.\d+)?)\s+(-?\d+(?:\.\d+)?)\s+-?\d+(?:\.\d+)?"""),
			"$1 $2"
		)
	}
}
