BEGIN;
INSERT INTO county (id, id_county, county, district_id) values (1, '01', 'Águeda', '01');
INSERT INTO county (id, id_county, county, district_id) values (2, '02', 'Albergaria-a-Velha', '01');
INSERT INTO county (id, id_county, county, district_id) values (3, '03', 'Anadia', '01');
INSERT INTO county (id, id_county, county, district_id) values (4, '04', 'Arouca', '01');
INSERT INTO county (id, id_county, county, district_id) values (5, '05', 'Aveiro', '01');
INSERT INTO county (id, id_county, county, district_id) values (6, '06', 'Castelo de Paiva', '01');
INSERT INTO county (id, id_county, county, district_id) values (7, '07', 'Espinho', '01');
INSERT INTO county (id, id_county, county, district_id) values (8, '08', 'Estarreja', '01');
INSERT INTO county (id, id_county, county, district_id) values (9, '09', 'Santa Maria da Feira', '01');
INSERT INTO county (id, id_county, county, district_id) values (10, '10', 'Ílhavo', '01');
INSERT INTO county (id, id_county, county, district_id) values (11, '11', 'Mealhada', '01');
INSERT INTO county (id, id_county, county, district_id) values (12, '12', 'Murtosa', '01');
INSERT INTO county (id, id_county, county, district_id) values (13, '13', 'Oliveira de Azeméis', '01');
INSERT INTO county (id, id_county, county, district_id) values (14, '14', 'Oliveira do Bairro', '01');
INSERT INTO county (id, id_county, county, district_id) values (15, '15', 'Ovar', '01');
INSERT INTO county (id, id_county, county, district_id) values (16, '16', 'São João da Madeira', '01');
INSERT INTO county (id, id_county, county, district_id) values (17, '17', 'Sever do Vouga', '01');
INSERT INTO county (id, id_county, county, district_id) values (18, '18', 'Vagos', '01');
INSERT INTO county (id, id_county, county, district_id) values (19, '19', 'Vale de Cambra', '01');

INSERT INTO county (id, id_county, county, district_id) values (20, '01', 'Aljustrel', '02');
INSERT INTO county (id, id_county, county, district_id) values (21, '02', 'Almodôvar', '02');
INSERT INTO county (id, id_county, county, district_id) values (22, '03', 'Alvito', '02');
INSERT INTO county (id, id_county, county, district_id) values (23, '04', 'Barrancos', '02');
INSERT INTO county (id, id_county, county, district_id) values (24, '05', 'Beja', '02');
INSERT INTO county (id, id_county, county, district_id) values (25, '06', 'Castro Verde', '02');
INSERT INTO county (id, id_county, county, district_id) values (26, '07', 'Cuba', '02');
INSERT INTO county (id, id_county, county, district_id) values (27, '08', 'Ferreira do Alentejo', '02');
INSERT INTO county (id, id_county, county, district_id) values (28, '09', 'Mértola', '02');
INSERT INTO county (id, id_county, county, district_id) values (29, '10', 'Moura', '02');
INSERT INTO county (id, id_county, county, district_id) values (30, '11', 'Odemira', '02');
INSERT INTO county (id, id_county, county, district_id) values (31, '12', 'Ourique', '02');
INSERT INTO county (id, id_county, county, district_id) values (32, '13', 'Serpa', '02');
INSERT INTO county (id, id_county, county, district_id) values (33, '14', 'Vidigueira', '02');

INSERT INTO county (id, id_county, county, district_id) values (34, '01', 'Amares', '03');
INSERT INTO county (id, id_county, county, district_id) values (35, '02', 'Barcelos', '03');
INSERT INTO county (id, id_county, county, district_id) values (36, '03', 'Braga', '03');
INSERT INTO county (id, id_county, county, district_id) values (37, '04', 'Cabeceiras de Basto', '03');
INSERT INTO county (id, id_county, county, district_id) values (38, '05', 'Celorico de Basto', '03');
INSERT INTO county (id, id_county, county, district_id) values (39, '06', 'Esposende', '03');
INSERT INTO county (id, id_county, county, district_id) values (40, '07', 'Fafe', '03');
INSERT INTO county (id, id_county, county, district_id) values (41, '08', 'Guimarães', '03');
INSERT INTO county (id, id_county, county, district_id) values (42, '09', 'Póvoa de Lanhoso', '03');
INSERT INTO county (id, id_county, county, district_id) values (43, '10', 'Terras de Bouro', '03');
INSERT INTO county (id, id_county, county, district_id) values (44, '11', 'Vieira do Minho', '03');
INSERT INTO county (id, id_county, county, district_id) values (45, '12', 'Vila Nova de Famalicão', '03');
INSERT INTO county (id, id_county, county, district_id) values (46, '13', 'Vila Verde', '03');
INSERT INTO county (id, id_county, county, district_id) values (47, '14', 'Vizela', '03');

INSERT INTO county (id, id_county, county, district_id) values (48, '01', 'Alfândega da Fé', '04');
INSERT INTO county (id, id_county, county, district_id) values (49, '02', 'Bragança', '04');
INSERT INTO county (id, id_county, county, district_id) values (50, '03', 'Carrazeda de Ansiães', '04');
INSERT INTO county (id, id_county, county, district_id) values (51, '04', 'Freixo de Espada à Cinta', '04');
INSERT INTO county (id, id_county, county, district_id) values (52, '05', 'Macedo de Cavaleiros', '04');
INSERT INTO county (id, id_county, county, district_id) values (53, '06', 'Miranda do Douro', '04');
INSERT INTO county (id, id_county, county, district_id) values (54, '07', 'Mirandela', '04');
INSERT INTO county (id, id_county, county, district_id) values (55, '08', 'Mogadouro', '04');
INSERT INTO county (id, id_county, county, district_id) values (56, '09', 'Torre de Moncorvo', '04');
INSERT INTO county (id, id_county, county, district_id) values (57, '10', 'Vila Flor', '04');
INSERT INTO county (id, id_county, county, district_id) values (58, '11', 'Vimioso', '04');
INSERT INTO county (id, id_county, county, district_id) values (59, '12', 'Vinhais', '04');

INSERT INTO county (id, id_county, county, district_id) values (60, '01', 'Belmonte', '05');
INSERT INTO county (id, id_county, county, district_id) values (61, '02', 'Castelo Branco', '05');
INSERT INTO county (id, id_county, county, district_id) values (62, '03', 'Covilhã', '05');
INSERT INTO county (id, id_county, county, district_id) values (63, '04', 'Fundão', '05');
INSERT INTO county (id, id_county, county, district_id) values (64, '05', 'Idanha-a-Nova', '05');
INSERT INTO county (id, id_county, county, district_id) values (65, '06', 'Oleiros', '05');
INSERT INTO county (id, id_county, county, district_id) values (66, '07', 'Penamacor', '05');
INSERT INTO county (id, id_county, county, district_id) values (67, '08', 'Proença-a-Nova', '05');
INSERT INTO county (id, id_county, county, district_id) values (68, '09', 'Sertã', '05');
INSERT INTO county (id, id_county, county, district_id) values (69, '10', 'Vila de Rei', '05');
INSERT INTO county (id, id_county, county, district_id) values (70, '11', 'Vila Velha de Ródão', '05');

INSERT INTO county (id, id_county, county, district_id) values (71, '01', 'Arganil', '06');
INSERT INTO county (id, id_county, county, district_id) values (72, '02', 'Cantanhede', '06');
INSERT INTO county (id, id_county, county, district_id) values (73, '03', 'Coimbra', '06');
INSERT INTO county (id, id_county, county, district_id) values (74, '04', 'Condeixa-a-Nova', '06');
INSERT INTO county (id, id_county, county, district_id) values (75, '05', 'Figueira da Foz', '06');
INSERT INTO county (id, id_county, county, district_id) values (76, '06', 'Góis', '06');
INSERT INTO county (id, id_county, county, district_id) values (77, '07', 'Lousã', '06');
INSERT INTO county (id, id_county, county, district_id) values (78, '08', 'Mira', '06');
INSERT INTO county (id, id_county, county, district_id) values (79, '09', 'Miranda do Corvo', '06');
INSERT INTO county (id, id_county, county, district_id) values (80, '10', 'Montemor-o-Velho', '06');
INSERT INTO county (id, id_county, county, district_id) values (81, '11', 'Oliveira do Hospital', '06');
INSERT INTO county (id, id_county, county, district_id) values (82, '12', 'Pampilhosa da Serra', '06');
INSERT INTO county (id, id_county, county, district_id) values (83, '13', 'Penacova', '06');
INSERT INTO county (id, id_county, county, district_id) values (84, '14', 'Penela', '06');
INSERT INTO county (id, id_county, county, district_id) values (85, '15', 'Soure', '06');
INSERT INTO county (id, id_county, county, district_id) values (86, '16', 'Tábua', '06');
INSERT INTO county (id, id_county, county, district_id) values (87, '17', 'Vila Nova de Poiares', '06');

INSERT INTO county (id, id_county, county, district_id) values (88, '01', 'Alandroal', '07');
INSERT INTO county (id, id_county, county, district_id) values (89, '02', 'Arraiolos', '07');
INSERT INTO county (id, id_county, county, district_id) values (90, '03', 'Borba', '07');
INSERT INTO county (id, id_county, county, district_id) values (91, '04', 'Estremoz', '07');
INSERT INTO county (id, id_county, county, district_id) values (92, '05', 'Évora', '07');
INSERT INTO county (id, id_county, county, district_id) values (93, '06', 'Montemor-o-Novo', '07');
INSERT INTO county (id, id_county, county, district_id) values (94, '07', 'Mora', '07');
INSERT INTO county (id, id_county, county, district_id) values (95, '08', 'Mourão', '07');
INSERT INTO county (id, id_county, county, district_id) values (96, '09', 'Portel', '07');
INSERT INTO county (id, id_county, county, district_id) values (97, '10', 'Redondo', '07');
INSERT INTO county (id, id_county, county, district_id) values (98, '11', 'Reguengos de Monsaraz', '07');
INSERT INTO county (id, id_county, county, district_id) values (99, '12', 'Vendas Novas', '07');
INSERT INTO county (id, id_county, county, district_id) values (100, '13', 'Viana do Alentejo', '07');
INSERT INTO county (id, id_county, county, district_id) values (101, '14', 'Vila Viçosa', '07');

INSERT INTO county (id, id_county, county, district_id) values (102, '01', 'Albufeira', '08');
INSERT INTO county (id, id_county, county, district_id) values (103, '02', 'Alcoutim', '08');
INSERT INTO county (id, id_county, county, district_id) values (104, '03', 'Aljezur', '08');
INSERT INTO county (id, id_county, county, district_id) values (105, '04', 'Castro Marim', '08');
INSERT INTO county (id, id_county, county, district_id) values (106, '05', 'Faro', '08');
INSERT INTO county (id, id_county, county, district_id) values (107, '06', 'Lagoa (Algarve)', '08');
INSERT INTO county (id, id_county, county, district_id) values (108, '07', 'Lagos', '08');
INSERT INTO county (id, id_county, county, district_id) values (109, '08', 'Loulé', '08');
INSERT INTO county (id, id_county, county, district_id) values (110, '09', 'Monchique', '08');
INSERT INTO county (id, id_county, county, district_id) values (111, '10', 'Olhão', '08');
INSERT INTO county (id, id_county, county, district_id) values (112, '11', 'Portimão', '08');
INSERT INTO county (id, id_county, county, district_id) values (113, '12', 'São Brás de Alportel', '08');
INSERT INTO county (id, id_county, county, district_id) values (114, '13', 'Silves', '08');
INSERT INTO county (id, id_county, county, district_id) values (115, '14', 'Tavira', '08');
INSERT INTO county (id, id_county, county, district_id) values (116, '15', 'Vila do Bispo', '08');
INSERT INTO county (id, id_county, county, district_id) values (117, '16', 'Vila Real de Santo António', '08');

INSERT INTO county (id, id_county, county, district_id) values (118, '01', 'Aguiar da Beira', '09');
INSERT INTO county (id, id_county, county, district_id) values (119, '02', 'Almeida', '09');
INSERT INTO county (id, id_county, county, district_id) values (120, '03', 'Celorico da Beira', '09');
INSERT INTO county (id, id_county, county, district_id) values (121, '04', 'Figueira de Castelo Rodrigo', '09');
INSERT INTO county (id, id_county, county, district_id) values (122, '05', 'Fornos de Algodres', '09');
INSERT INTO county (id, id_county, county, district_id) values (123, '06', 'Gouveia', '09');
INSERT INTO county (id, id_county, county, district_id) values (124, '07', 'Guarda', '09');
INSERT INTO county (id, id_county, county, district_id) values (125, '08', 'Manteigas', '09');
INSERT INTO county (id, id_county, county, district_id) values (126, '09', 'Meda', '09');
INSERT INTO county (id, id_county, county, district_id) values (127, '10', 'Pinhel', '09');
INSERT INTO county (id, id_county, county, district_id) values (128, '11', 'Sabugal', '09');
INSERT INTO county (id, id_county, county, district_id) values (129, '12', 'Seia', '09');
INSERT INTO county (id, id_county, county, district_id) values (130, '13', 'Trancoso', '09');
INSERT INTO county (id, id_county, county, district_id) values (131, '14', 'Vila Nova de Foz Côa', '09');

INSERT INTO county (id, id_county, county, district_id) values (132, '01', 'Alcobaça', '10');
INSERT INTO county (id, id_county, county, district_id) values (133, '02', 'Alvaiázere', '10');
INSERT INTO county (id, id_county, county, district_id) values (134, '03', 'Ansião', '10');
INSERT INTO county (id, id_county, county, district_id) values (135, '04', 'Batalha', '10');
INSERT INTO county (id, id_county, county, district_id) values (136, '05', 'Bombarral', '10');
INSERT INTO county (id, id_county, county, district_id) values (137, '06', 'Caldas da Rainha', '10');
INSERT INTO county (id, id_county, county, district_id) values (138, '07', 'Castanheira de Pêra', '10');
INSERT INTO county (id, id_county, county, district_id) values (139, '08', 'Figueiró dos Vinhos', '10');
INSERT INTO county (id, id_county, county, district_id) values (140, '09', 'Leiria', '10');
INSERT INTO county (id, id_county, county, district_id) values (141, '10', 'Marinha Grande', '10');
INSERT INTO county (id, id_county, county, district_id) values (142, '11', 'Nazaré', '10');
INSERT INTO county (id, id_county, county, district_id) values (143, '12', 'Óbidos', '10');
INSERT INTO county (id, id_county, county, district_id) values (144, '13', 'Pedrógão Grande', '10');
INSERT INTO county (id, id_county, county, district_id) values (145, '14', 'Peniche', '10');
INSERT INTO county (id, id_county, county, district_id) values (146, '15', 'Pombal', '10');
INSERT INTO county (id, id_county, county, district_id) values (147, '16', 'Porto de Mós', '10');

INSERT INTO county (id, id_county, county, district_id) values (148, '02', 'Arruda dos Vinhos', '11');
INSERT INTO county (id, id_county, county, district_id) values (149, '03', 'Azambuja', '11');
INSERT INTO county (id, id_county, county, district_id) values (150, '04', 'Cadaval', '11');
INSERT INTO county (id, id_county, county, district_id) values (151, '05', 'Cascais', '11');
INSERT INTO county (id, id_county, county, district_id) values (152, '06', 'Lisboa', '11');
INSERT INTO county (id, id_county, county, district_id) values (153, '07', 'Loures', '11');
INSERT INTO county (id, id_county, county, district_id) values (154, '08', 'Lourinhã', '11');
INSERT INTO county (id, id_county, county, district_id) values (155, '09', 'Mafra', '11');
INSERT INTO county (id, id_county, county, district_id) values (156, '10', 'Oeiras', '11');
INSERT INTO county (id, id_county, county, district_id) values (157, '11', 'Sintra', '11');
INSERT INTO county (id, id_county, county, district_id) values (158, '12', 'Sobral de Monte Agraço', '11');
INSERT INTO county (id, id_county, county, district_id) values (159, '13', 'Torres Vedras', '11');
INSERT INTO county (id, id_county, county, district_id) values (160, '14', 'Vila Franca de Xira', '11');
INSERT INTO county (id, id_county, county, district_id) values (161, '15', 'Amadora', '11');
INSERT INTO county (id, id_county, county, district_id) values (162, '16', 'Odivelas', '11');
INSERT INTO county (id, id_county, county, district_id) values (163, '01', 'Alenquer', '11');

INSERT INTO county (id, id_county, county, district_id) values (179, '01', 'Alter do Chão', '12');
INSERT INTO county (id, id_county, county, district_id) values (180, '02', 'Arronches', '12');
INSERT INTO county (id, id_county, county, district_id) values (181, '03', 'Avis', '12');
INSERT INTO county (id, id_county, county, district_id) values (182, '04', 'Campo Maior', '12');
INSERT INTO county (id, id_county, county, district_id) values (183, '05', 'Castelo de Vide', '12');
INSERT INTO county (id, id_county, county, district_id) values (184, '06', 'Crato', '12');
INSERT INTO county (id, id_county, county, district_id) values (185, '07', 'Elvas', '12');
INSERT INTO county (id, id_county, county, district_id) values (186, '08', 'Fronteira', '12');
INSERT INTO county (id, id_county, county, district_id) values (187, '09', 'Gavião', '12');
INSERT INTO county (id, id_county, county, district_id) values (188, '10', 'Marvão', '12');
INSERT INTO county (id, id_county, county, district_id) values (189, '11', 'Monforte', '12');
INSERT INTO county (id, id_county, county, district_id) values (190, '12', 'Nisa', '12');
INSERT INTO county (id, id_county, county, district_id) values (191, '13', 'Ponte de Sor', '12');
INSERT INTO county (id, id_county, county, district_id) values (192, '14', 'Portalegre', '12');
INSERT INTO county (id, id_county, county, district_id) values (193, '15', 'Sousel', '12');

INSERT INTO county (id, id_county, county, district_id) values (194, '01', 'Amarante', '13');   
INSERT INTO county (id, id_county, county, district_id) values (195, '02', 'Baião', '13');
INSERT INTO county (id, id_county, county, district_id) values (196, '03', 'Felgueiras', '13');
INSERT INTO county (id, id_county, county, district_id) values (197, '04', 'Gondomar', '13');
INSERT INTO county (id, id_county, county, district_id) values (198, '05', 'Lousada', '13');
INSERT INTO county (id, id_county, county, district_id) values (199, '06', 'Maia', '13');
INSERT INTO county (id, id_county, county, district_id) values (200, '07', 'Marco de Canaveses', '13');
INSERT INTO county (id, id_county, county, district_id) values (201, '08', 'Matosinhos', '13');
INSERT INTO county (id, id_county, county, district_id) values (202, '09', 'Paços de Ferreira', '13');
INSERT INTO county (id, id_county, county, district_id) values (203, '10', 'Paredes', '13');
INSERT INTO county (id, id_county, county, district_id) values (204, '11', 'Penafiel', '13');
INSERT INTO county (id, id_county, county, district_id) values (205, '12', 'Porto', '13');
INSERT INTO county (id, id_county, county, district_id) values (206, '13', 'Póvoa de Varzim', '13');
INSERT INTO county (id, id_county, county, district_id) values (207, '14', 'Santo Tirso', '13');
INSERT INTO county (id, id_county, county, district_id) values (208, '18', 'Trofa', '13');
INSERT INTO county (id, id_county, county, district_id) values (209, '15', 'Valongo', '13');
INSERT INTO county (id, id_county, county, district_id) values (210, '16', 'Vila do Conde', '13');
INSERT INTO county (id, id_county, county, district_id) values (211, '17', 'Vila Nova de Gaia', '13');

INSERT INTO county (id, id_county, county, district_id) values (212, '01', 'Abrantes', '14');
INSERT INTO county (id, id_county, county, district_id) values (213, '02', 'Alcanena', '14');
INSERT INTO county (id, id_county, county, district_id) values (214, '03', 'Almeirim', '14');
INSERT INTO county (id, id_county, county, district_id) values (215, '04', 'Alpiarça', '14');
INSERT INTO county (id, id_county, county, district_id) values (216, '05', 'Benavente', '14');
INSERT INTO county (id, id_county, county, district_id) values (217, '06', 'Cartaxo', '14');
INSERT INTO county (id, id_county, county, district_id) values (218, '07', 'Chamusca', '14');
INSERT INTO county (id, id_county, county, district_id) values (219, '08', 'Constância', '14');
INSERT INTO county (id, id_county, county, district_id) values (220, '09', 'Coruche', '14');
INSERT INTO county (id, id_county, county, district_id) values (221, '10', 'Entroncamento', '14');
INSERT INTO county (id, id_county, county, district_id) values (222, '11', 'Ferreira do Zêzere', '14');
INSERT INTO county (id, id_county, county, district_id) values (223, '12', 'Golegã', '14');
INSERT INTO county (id, id_county, county, district_id) values (224, '13', 'Mação', '14');
INSERT INTO county (id, id_county, county, district_id) values (225, '21', 'Ourém', '14');
INSERT INTO county (id, id_county, county, district_id) values (226, '14', 'Rio Maior', '14');
INSERT INTO county (id, id_county, county, district_id) values (227, '15', 'Salvaterra de Magos', '14');
INSERT INTO county (id, id_county, county, district_id) values (228, '16', 'Santarém', '14');
INSERT INTO county (id, id_county, county, district_id) values (229, '17', 'Sardoal', '14');
INSERT INTO county (id, id_county, county, district_id) values (230, '18', 'Tomar', '14');
INSERT INTO county (id, id_county, county, district_id) values (231, '19', 'Torres Novas', '14');
INSERT INTO county (id, id_county, county, district_id) values (232, '20', 'Vila Nova da Barquinha', '14');

INSERT INTO county (id, id_county, county, district_id) values (233, '01', 'Alcácer do Sal', '15');
INSERT INTO county (id, id_county, county, district_id) values (234, '02', 'Alcochete', '15');
INSERT INTO county (id, id_county, county, district_id) values (235, '03', 'Almada', '15');
INSERT INTO county (id, id_county, county, district_id) values (236, '04', 'Barreiro', '15');
INSERT INTO county (id, id_county, county, district_id) values (237, '05', 'Grândola', '15');
INSERT INTO county (id, id_county, county, district_id) values (238, '06', 'Moita', '15');
INSERT INTO county (id, id_county, county, district_id) values (239, '07', 'Montijo', '15');
INSERT INTO county (id, id_county, county, district_id) values (240, '08', 'Palmela', '15');
INSERT INTO county (id, id_county, county, district_id) values (241, '09', 'Santiago do Cacém', '15');
INSERT INTO county (id, id_county, county, district_id) values (242, '10', 'Seixal', '15');
INSERT INTO county (id, id_county, county, district_id) values (243, '11', 'Sesimbra', '15');
INSERT INTO county (id, id_county, county, district_id) values (244, '12', 'Setúbal', '15');
INSERT INTO county (id, id_county, county, district_id) values (245, '13', 'Sines', '15');

INSERT INTO county (id, id_county, county, district_id) values (246, '01', 'Arcos de Valdevez', '16');
INSERT INTO county (id, id_county, county, district_id) values (247, '02', 'Caminha', '16');
INSERT INTO county (id, id_county, county, district_id) values (248, '03', 'Melgaço', '16');
INSERT INTO county (id, id_county, county, district_id) values (249, '04', 'Monção', '16');
INSERT INTO county (id, id_county, county, district_id) values (250, '05', 'Paredes de Coura', '16');
INSERT INTO county (id, id_county, county, district_id) values (251, '06', 'Ponte da Barca', '16');
INSERT INTO county (id, id_county, county, district_id) values (252, '07', 'Ponte de Lima', '16');
INSERT INTO county (id, id_county, county, district_id) values (253, '08', 'Valença', '16');
INSERT INTO county (id, id_county, county, district_id) values (254, '09', 'Viana do Castelo', '16');
INSERT INTO county (id, id_county, county, district_id) values (255, '10', 'Vila Nova de Cerveira', '16');

INSERT INTO county (id, id_county, county, district_id) values (256, '01', 'Alijó', '17');
INSERT INTO county (id, id_county, county, district_id) values (257, '02', 'Boticas', '17');
INSERT INTO county (id, id_county, county, district_id) values (258, '03', 'Chaves', '17');
INSERT INTO county (id, id_county, county, district_id) values (259, '04', 'Mesão Frio', '17');
INSERT INTO county (id, id_county, county, district_id) values (260, '05', 'Mondim de Basto', '17');
INSERT INTO county (id, id_county, county, district_id) values (261, '06', 'Montalegre', '17');
INSERT INTO county (id, id_county, county, district_id) values (262, '07', 'Murça', '17');
INSERT INTO county (id, id_county, county, district_id) values (263, '08', 'Peso da Régua', '17');
INSERT INTO county (id, id_county, county, district_id) values (264, '09', 'Ribeira de Pena', '17');
INSERT INTO county (id, id_county, county, district_id) values (265, '10', 'Sabrosa', '17');
INSERT INTO county (id, id_county, county, district_id) values (266, '11', 'Santa Marta de Penaguião', '17');
INSERT INTO county (id, id_county, county, district_id) values (267, '12', 'Valpaços', '17');
INSERT INTO county (id, id_county, county, district_id) values (268, '13', 'Vila Pouca de Aguiar', '17');
INSERT INTO county (id, id_county, county, district_id) values (269, '14', 'Vila Real', '17');

INSERT INTO county (id, id_county, county, district_id) values (270, '01', 'Armamar', '18');
INSERT INTO county (id, id_county, county, district_id) values (271, '02', 'Carregal do Sal', '18');
INSERT INTO county (id, id_county, county, district_id) values (272, '03', 'Castro Daire', '18');
INSERT INTO county (id, id_county, county, district_id) values (273, '04', 'Cinfães', '18');
INSERT INTO county (id, id_county, county, district_id) values (274, '05', 'Lamego', '18');
INSERT INTO county (id, id_county, county, district_id) values (275, '06', 'Mangualde', '18');
INSERT INTO county (id, id_county, county, district_id) values (276, '07', 'Moimenta da Beira', '18');
INSERT INTO county (id, id_county, county, district_id) values (277, '08', 'Mortágua', '18');
INSERT INTO county (id, id_county, county, district_id) values (278, '09', 'Nelas', '18');
INSERT INTO county (id, id_county, county, district_id) values (279, '10', 'Oliveira de Frades', '18');
INSERT INTO county (id, id_county, county, district_id) values (280, '11', 'Penalva do Castelo', '18');
INSERT INTO county (id, id_county, county, district_id) values (281, '12', 'Penedono', '18');
INSERT INTO county (id, id_county, county, district_id) values (282, '13', 'Resende', '18');
INSERT INTO county (id, id_county, county, district_id) values (283, '14', 'Santa Comba Dão', '18');
INSERT INTO county (id, id_county, county, district_id) values (284, '15', 'São João da Pesqueira', '18');
INSERT INTO county (id, id_county, county, district_id) values (285, '16', 'São Pedro do Sul', '18');
INSERT INTO county (id, id_county, county, district_id) values (286, '17', 'Sátão', '18');
INSERT INTO county (id, id_county, county, district_id) values (287, '18', 'Sernancelhe', '18');
INSERT INTO county (id, id_county, county, district_id) values (288, '19', 'Tabuaço', '18');
INSERT INTO county (id, id_county, county, district_id) values (289, '20', 'Tarouca', '18');
INSERT INTO county (id, id_county, county, district_id) values (290, '21', 'Tondela', '18');
INSERT INTO county (id, id_county, county, district_id) values (291, '22', 'Vila Nova de Paiva', '18');
INSERT INTO county (id, id_county, county, district_id) values (292, '23', 'Viseu', '18');
INSERT INTO county (id, id_county, county, district_id) values (293, '24', 'Vouzela', '18');

INSERT INTO county (id, id_county, county, district_id) values (294, '01', 'Calheta (Madeira)', '31');
INSERT INTO county (id, id_county, county, district_id) values (295, '02', 'Câmara de Lobos', '31');
INSERT INTO county (id, id_county, county, district_id) values (296, '03', 'Funchal', '31');
INSERT INTO county (id, id_county, county, district_id) values (297, '04', 'Machico', '31');
INSERT INTO county (id, id_county, county, district_id) values (298, '05', 'Ponta do Sol', '31');
INSERT INTO county (id, id_county, county, district_id) values (299, '06', 'Porto Moniz', '31');
INSERT INTO county (id, id_county, county, district_id) values (300, '07', 'Ribeira Brava', '31');
INSERT INTO county (id, id_county, county, district_id) values (301, '08', 'Santa Cruz', '31');
INSERT INTO county (id, id_county, county, district_id) values (302, '09', 'Santana', '31');
INSERT INTO county (id, id_county, county, district_id) values (303, '10', 'São Vicente', '31');


-- FALTA INSERIR OS RESTANTES CONCELHOS da MADEIRA e AÇORES
COMMIT;