BEGIN;
INSERT INTO district (id, district, country_id) VALUES ('01', 'Aveiro', 'Portugal');
INSERT INTO district (id, district, country_id) VALUES ('02', 'Beja', 'Portugal');
INSERT INTO district (id, district, country_id) VALUES ('03', 'Braga', 'Portugal');
INSERT INTO district (id, district, country_id) VALUES ('04', 'Bragança', 'Portugal');
INSERT INTO district (id, district, country_id) VALUES ('05', 'Castelo Branco', 'Portugal');
INSERT INTO district (id, district, country_id) VALUES ('06', 'Coimbra', 'Portugal');
INSERT INTO district (id, district, country_id) VALUES ('07', 'Évora', 'Portugal');
INSERT INTO district (id, district, country_id) VALUES ('08', 'Faro', 'Portugal');
INSERT INTO district (id, district, country_id) VALUES ('09', 'Guarda', 'Portugal');
INSERT INTO district (id, district, country_id) VALUES ('10', 'Leiria', 'Portugal');
INSERT INTO district (id, district, country_id) VALUES ('11', 'Lisboa', 'Portugal');
INSERT INTO district (id, district, country_id) VALUES ('12', 'Portalegre', 'Portugal');
INSERT INTO district (id, district, country_id) VALUES ('13', 'Porto', 'Portugal');
INSERT INTO district (id, district, country_id) VALUES ('14', 'Santarém', 'Portugal');
INSERT INTO district (id, district, country_id) VALUES ('15', 'Setúbal', 'Portugal');
INSERT INTO district (id, district, country_id) VALUES ('16', 'Viana do Castelo', 'Portugal');
INSERT INTO district (id, district, country_id) VALUES ('17', 'Vila Real', 'Portugal');
INSERT INTO district (id, district, country_id) VALUES ('18', 'Viseu', 'Portugal');
INSERT INTO district (id, district, country_id) VALUES ('31', 'Ilha da Madeira', 'Portugal');
INSERT INTO district (id, district, country_id) VALUES ('32', 'Ilha de Porto Santo', 'Portugal');
INSERT INTO district (id, district, country_id) VALUES ('41', 'Ilha de Santa Maria', 'Portugal');
INSERT INTO district (id, district, country_id) VALUES ('42', 'Ilha de São Miguel', 'Portugal');
INSERT INTO district (id, district, country_id) VALUES ('43', 'Ilha Terceira', 'Portugal');
INSERT INTO district (id, district, country_id) VALUES ('44', 'Ilha Graciosa', 'Portugal');
INSERT INTO district (id, district, country_id) VALUES ('45', 'Ilha de São Jorge', 'Portugal');
INSERT INTO district (id, district, country_id) VALUES ('46', 'Ilha do Pico', 'Portugal');
INSERT INTO district (id, district, country_id) VALUES ('47', 'Ilha do Faial', 'Portugal');
INSERT INTO district (id, district, country_id) VALUES ('48', 'Ilha das Flores', 'Portugal');
INSERT INTO district (id, district, country_id) VALUES ('49', 'Ilha do Corvo', 'Portugal');
COMMIT;