spring.application.name=geocell

# PostgreSQL Configurations
# TODO: CHANGE BY ENVIRONMENT VARIABLES (/etc/environment)
spring.datasource.url=jdbc:postgresql://localhost:5432/geocell
spring.datasource.username=geocell_user
spring.datasource.password=4w5_Yd4xee35$
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Additional Configurations
spring.jpa.open-in-view=false