-- Criar extensões
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Department, some departments will have access to Operations, other only normal search / analysis
CREATE TABLE department(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    have_operations BOOLEAN NOT NULL
);

-- User
-- normal users can do simple searches, analyst users can do more complex searches,
-- if user belongs to a department with Operations, he can view the operation or in case
-- of 'is_operation_admin', he can edit Department Operations.
-- Superuser is for webapp / DB admin, can view logs, create/delete users/departments, deactivate users
CREATE TABLE auth_user (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username           VARCHAR(150) UNIQUE      NOT NULL,
    password           VARCHAR(128)             NOT NULL,
    name               VARCHAR(150)             NOT NULL,
    email              VARCHAR(254)             NOT NULL,
    date_joined        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    last_login         TIMESTAMP WITH TIME ZONE,
    is_active          BOOLEAN                  NOT NULL DEFAULT true,
    is_superuser       BOOLEAN                  NOT NULL,
    is_analyst         BOOLEAN                  NOT NULL,
    is_operation_admin BOOLEAN                  NOT NULL,
    map_type           VARCHAR(9)               NOT NULL DEFAULT 'standard' CHECK (map_type IN ('standard', 'satellite', 'hybrid', 'terrain')),
    show_grid          BOOLEAN                  NOT NULL DEFAULT false,
    show_counties      BOOLEAN                  NOT NULL DEFAULT false
);
CREATE INDEX idx_auth_user_username ON auth_user(username varchar_pattern_ops);
CREATE INDEX idx_auth_user_id ON auth_user(id);

CREATE TABLE user_department(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE,
    department_id INT NOT NULL REFERENCES department(id) ON DELETE CASCADE
);

-- Session
CREATE TABLE session(
    session_key VARCHAR(40) PRIMARY KEY,
    session_data BYTEA NOT NULL,
    expire_date TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_session_key ON session(session_key);
CREATE INDEX idx_session_expire_date ON session(expire_date);

CREATE TABLE active_user_session(
    user_id INTEGER PRIMARY KEY REFERENCES auth_user(id) ON DELETE CASCADE,
    session_key VARCHAR(40) UNIQUE NOT NULL REFERENCES session(session_key) ON DELETE CASCADE,
    last_heartbeat TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, -- For SSE heartbeat
    connection_id UUID DEFAULT gen_random_uuid(),
    sse_connection_count INTEGER DEFAULT 0,
    ip_address INET,  -- For aditional security
    user_agent TEXT  -- For auditory
);
CREATE INDEX idx_active_user_session_user_id ON active_user_session(user_id);
CREATE INDEX idx_active_user_session_session_key ON active_user_session(session_key varchar_pattern_ops);
CREATE INDEX idx_active_user_session_updated_at ON active_user_session(last_heartbeat);

CREATE TABLE admin_log(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_time TIMESTAMP WITH TIME ZONE NOT NULL,
    object_id TEXT,
    object_repr VARCHAR(200),
    action_flag SMALLINT NOT NULL CHECK ( action_flag >= 0 ),
    change_message TEXT NOT NULL,
    user_id INTEGER NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE
);

-- GEOLOCATION TABLES ==========================================================================
CREATE TABLE caop_23p(
    ogc_fid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wkb_geometry GEOMETRY(MultiPolygon,4326) NOT NULL,
    fid INTEGER NOT NULL,
    dicofre VARCHAR(6) NOT NULL,
    area_ha DOUBLE PRECISION NOT NULL,
    des_simpli VARCHAR(255) NOT NULL,
    layer TEXT NOT NULL,
    path TEXT,
    freguesia TEXT NOT NULL,
    concelho TEXT NOT NULL,
    concelho_cd TEXT NOT NULL,
    distrito TEXT NOT NULL,
    distrito_cd TEXT NOT NULL
);
CREATE INDEX idx_caop_23p_wkb_geometry ON caop_23p USING GIST (wkb_geometry);
CREATE INDEX idx_caop_23p_dicofre ON caop_23p (dicofre);
CREATE INDEX idx_caop_23p_concelho ON caop_23p (concelho);
CREATE INDEX idx_caop_23p_distrito ON caop_23p (distrito);
CREATE INDEX idx_caop_23p_concelho_dicofre ON caop_23p (concelho, dicofre);
CREATE INDEX idx_caop_23p_geometry ON caop_23p USING GIST (wkb_geometry);
CREATE INDEX idx_caop_23p_geometry_concelho ON caop_23p (concelho, wkb_geometry);
CREATE INDEX idx_caop_23p_geometry_distrito ON caop_23p (distrito, wkb_geometry);

CREATE TABLE country (
    name VARCHAR(100) NOT NULL,
    code VARCHAR(4) UNIQUE,
    polygon GEOMETRY(Polygon, 4326),
    flag VARCHAR(100),
    PRIMARY KEY (name)
);
CREATE INDEX idx_country_name_b2be7d8b_like ON country (name varchar_pattern_ops);
CREATE INDEX idx_country_polygon_id ON country USING GIST (polygon);

CREATE TABLE district (
    id VARCHAR(20) PRIMARY KEY,
    district VARCHAR(100) NOT NULL,
    polygon GEOMETRY(Polygon, 4326),
    country_id VARCHAR(100) NOT NULL REFERENCES country(name) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX idx_district_country_id ON district (country_id);
CREATE INDEX idx_district_country_id_like ON district (country_id varchar_pattern_ops);
CREATE INDEX idx_district_id_like ON district (id varchar_pattern_ops);
CREATE INDEX idx_district_polygon_id ON district USING GIST (polygon);
CREATE INDEX idx_district_country_id_polygon ON district (country_id, polygon);

CREATE TABLE county (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_county VARCHAR(20) NOT NULL,
    county VARCHAR(100) NOT NULL,
    polygon GEOMETRY(Polygon, 4326),
    district_id VARCHAR(20) REFERENCES district(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX idx_county_district_id ON county (district_id);
CREATE INDEX idx_county_district_id_like ON county (district_id varchar_pattern_ops);
CREATE UNIQUE INDEX idx_county_district_id_id_uniq ON county (district_id, id);
CREATE INDEX idx_county_polygon_id ON county USING GIST (polygon);

CREATE TABLE portugal_grid_500m (
    cell_id VARCHAR(10) PRIMARY KEY,
    center_geom GEOMETRY(Point, 4326) NOT NULL,
    bbox_geom GEOMETRY(Polygon, 4326) NOT NULL,
    grid_row INTEGER NOT NULL,
    grid_col INTEGER NOT NULL
);
CREATE INDEX idx_portugal_grid_center_geom ON portugal_grid_500m USING GIST (center_geom);
CREATE INDEX idx_portugal_grid_bbox_geom ON portugal_grid_500m USING GIST (bbox_geom);
CREATE INDEX idx_portugal_grid_cell_id_like ON portugal_grid_500m (cell_id varchar_pattern_ops);

CREATE TABLE location (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coordinates GEOMETRY(Point, 4326),
    address VARCHAR(100),
    address1 VARCHAR(100),
    zip4 INTEGER NOT NULL,
    zip3 INTEGER NOT NULL,
    postal_designation VARCHAR(100),
    id_county_id BIGINT REFERENCES county(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX idx_location_coordinates_id ON location USING GIST (coordinates);
CREATE INDEX idx_location_id_county_id ON location (id_county_id);

-- CELL RELATED TABLES ============================================================================
CREATE TABLE mccmnc (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(100),
    mcc INTEGER NOT NULL,
    mnc INTEGER NOT NULL,
    brand VARCHAR(100),
    operator VARCHAR(200),
    status VARCHAR(100),
    bands VARCHAR(200),
    notes VARCHAR(300),
    country_id VARCHAR(100) REFERENCES country(name) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX idx_mccmnc_country_id ON mccmnc (country_id);
CREATE INDEX idx_mccmnc_country_id_like ON mccmnc (country_id varchar_pattern_ops);
CREATE UNIQUE INDEX idx_mccmnc_mcc_mnc_uniq ON mccmnc (mcc, mnc);

CREATE TABLE enbgnb (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enb_gnb INTEGER NOT NULL,
    location_id BIGINT NOT NULL REFERENCES location(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX idx_enbgnb_location_id ON enbgnb (location_id);

CREATE TABLE band (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    band VARCHAR(50),
    bandwidth DOUBLE PRECISION,
    uplink_freq DOUBLE PRECISION,
    downlink_freq DOUBLE PRECISION,
    earfcn DOUBLE PRECISION
);
CREATE INDEX idx_geocell_band_band ON band (band);
CREATE INDEX idx_geocell_band_earfcn ON band (earfcn);

CREATE TABLE cell (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lac_tac VARCHAR(50),
    ci VARCHAR(20),
    eci_nci VARCHAR(20),
    cgi VARCHAR(30) CHECK (
        cgi IS NULL OR
        cgi ~ '^\d{3}-\d{2,3}-\d{1,11}$' OR  -- 4G/5G: MCC-MNC-ECI/NCI
        cgi ~ '^\d{3}-\d{2,3}-\d{1,5}-\d{1,11}$'  -- 2G/3G: MCC-MNC-LAC-CI
        ),
    paragon_cgi VARCHAR(100),
    technology INTEGER NOT NULL CHECK (technology IN (2, 3, 4, 5, 10)), -- 10 for NB-IoT
    azimuth INTEGER NOT NULL CHECK (azimuth >= 0 AND azimuth <= 360),
    name VARCHAR(200),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    band_id BIGINT REFERENCES band(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    enb_gnb_id BIGINT REFERENCES enbgnb(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    location_id BIGINT REFERENCES location(id) DEFERRABLE INITIALLY DEFERRED,
    mcc_mnc_id BIGINT REFERENCES mccmnc(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    updated_by INTEGER REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED,
    created_by INTEGER REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX idx_cell_band_id ON cell (band_id);
CREATE INDEX idx_cell_cgi ON cell (cgi);
CREATE INDEX idx_cell_cgi_like ON cell (cgi varchar_pattern_ops);
CREATE UNIQUE INDEX idx_cell_cgi_paragon_cgi_azimuth_uniq
    ON cell (cgi, paragon_cgi, azimuth);
CREATE INDEX idx_cell_enb_gnb_id ON cell (enb_gnb_id);
CREATE INDEX idx_cell_location_id ON cell (location_id);
CREATE INDEX idx_cell_mcc_mnc_id ON cell (mcc_mnc_id);
CREATE INDEX idx_cell_updated_by_id ON cell (updated_by);
CREATE INDEX idx_cell_created_by_id ON cell (created_by);
CREATE INDEX idx_cell_paragon_cgi ON cell (paragon_cgi);
CREATE INDEX idx_cell_paragon_cgi_like ON cell (paragon_cgi varchar_pattern_ops);
CREATE INDEX idx_cell_technology ON cell (technology);
CREATE INDEX idx_cell_azimuth ON cell (azimuth);
CREATE INDEX idx_cell_created ON cell (created_at);
CREATE INDEX idx_cell_modified ON cell (updated_at);
CREATE INDEX idx_cell_location_technology ON cell (location_id, technology);
CREATE INDEX idx_cell_band_technology ON cell (band_id, technology);
CREATE INDEX idx_cell_location_coords ON cell (location_id) WHERE location_id IS NOT NULL;

CREATE TABLE cell_polygon (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    polygon GEOGRAPHY(PolygonZ, 4326) NOT NULL,
    cell_id BIGINT REFERENCES cell(id) ON DELETE CASCADE,
    polygon_short GEOGRAPHY(PolygonZ, 4326) NOT NULL
);
CREATE INDEX idx_cell_polygon_cell_id ON cell_polygon (cell_id);
CREATE INDEX idx_cell_polygon_polygon_id ON cell_polygon USING GIST (polygon);
CREATE INDEX idx_cell_polygon_polygon_short_id ON cell_polygon USING GIST (polygon_short);

-- OPERATION RELATED TABLES ===============================================================================

CREATE TABLE operation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    department_id INTEGER NOT NULL REFERENCES department(id) DEFERRABLE INITIALLY DEFERRED,
    active BOOLEAN NOT NULL,
    modified TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_operation_department_id ON operation (department_id);
CREATE UNIQUE INDEX idx_operation_name_department_id_uniq
    ON operation (name, department_id);

CREATE TABLE operation_target (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(256) NOT NULL CHECK (TRIM(name) <> ''),
    operation_id BIGINT NOT NULL REFERENCES operation(id) DEFERRABLE INITIALLY DEFERRED,
    color VARCHAR(7) NOT NULL CHECK (color ~ '^#[0-9A-Fa-f]{6}$')
);
CREATE INDEX idx_operation_target_operation_id ON operation_target (operation_id);
CREATE UNIQUE INDEX idx_operation_target_name_operation_id_uniq
    ON operation_target (name, operation_id);
CREATE UNIQUE INDEX idx_operation_target_color_operation_id_uniq
    ON operation_target (color, operation_id);

CREATE TABLE operation_cell (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_time TIMESTAMP WITH TIME ZONE,
    cell_id BIGINT NOT NULL REFERENCES cell(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    target_id BIGINT NOT NULL REFERENCES operation_target(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    user_id INTEGER NOT NULL REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX idx_operation_cell_cell_id ON operation_cell (cell_id);
CREATE INDEX idx_operation_cell_target_id ON operation_cell (target_id);
CREATE INDEX idx_operation_cell_user_id ON operation_cell (user_id);
CREATE INDEX idx_operation_cell_timestamp ON operation_cell (timestamp);
CREATE INDEX idx_operation_cell_timestamp_range ON operation_cell (timestamp, cell_id);
CREATE INDEX idx_operation_cell_user_time ON operation_cell (user_time);
CREATE INDEX idx_operation_cell_cell_target ON operation_cell (cell_id, target_id);
CREATE INDEX idx_operation_cell_user_timestamp ON operation_cell (user_id, timestamp DESC);

CREATE TABLE operation_poi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL CHECK (TRIM(name) <> ''),
    description TEXT,
    latitude DOUBLE PRECISION NOT NULL CHECK (latitude BETWEEN -90 AND 90),
    longitude DOUBLE PRECISION NOT NULL CHECK (longitude BETWEEN -180 AND 180),
    icon VARCHAR(21) NOT NULL CHECK (TRIM(icon) <> ''),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    target_id BIGINT NOT NULL REFERENCES operation_target(id) DEFERRABLE INITIALLY DEFERRED,
    user_id INTEGER NOT NULL REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX idx_operation_poi_target_id ON operation_poi (target_id);
CREATE INDEX idx_operation_poi_user_id ON operation_poi (user_id);
CREATE UNIQUE INDEX idx_operation_poi_name_target_id_uniq
    ON operation_poi (name, target_id);
CREATE UNIQUE INDEX idx_operation_poi_target_id_lat_lon_uniq
    ON operation_poi (target_id, latitude, longitude);
CREATE INDEX idx_operation_poi_created_at ON operation_poi (created_at);
CREATE INDEX idx_operation_poi_coordinates ON operation_poi (latitude, longitude);

CREATE TABLE operation_user_cell (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_time TIMESTAMP WITH TIME ZONE,
    cgi VARCHAR(30) CHECK (
        cgi IS NULL OR
        cgi ~ '^\d{3}-\d{2,3}-\d{1,11}$' OR  -- 4G/5G: MCC-MNC-ECI/NCI
        cgi ~ '^\d{3}-\d{2,3}-\d{1,5}-\d{1,11}$'  -- 2G/3G: MCC-MNC-LAC-CI
        ),
    technology INTEGER CHECK (technology IN (2, 3, 4, 5, 10)),
    name VARCHAR(256),
    notes TEXT,
    coordinates GEOMETRY(Point, 4326) NOT NULL,
    direction INTEGER NOT NULL CHECK (direction >= 0 AND direction <= 360),
    target_id BIGINT NOT NULL REFERENCES operation_target(id) DEFERRABLE INITIALLY DEFERRED,
    user_id INTEGER NOT NULL REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX idx_operation_user_cell_target_id ON operation_user_cell (target_id);
CREATE INDEX idx_operation_user_cell_user_id ON operation_user_cell (user_id);
CREATE INDEX idx_operation_user_cell_coordinates ON operation_user_cell USING GIST (coordinates);
CREATE INDEX idx_operation_user_cell_timestamp ON operation_user_cell (timestamp);
CREATE INDEX idx_operation_user_cell_technology ON operation_user_cell (technology);
CREATE INDEX idx_operation_user_cell_cgi ON operation_user_cell (cgi);
CREATE INDEX idx_operation_user_cell_user_timestamp ON operation_user_cell (user_id, timestamp DESC);
CREATE INDEX idx_operation_user_cell_target_timestamp ON operation_user_cell (target_id, timestamp DESC);
CREATE INDEX idx_operation_user_cell_timestamp_range ON operation_user_cell (timestamp, user_id);

-- USER RELATED TABLES ======================================================================================
CREATE TABLE user_activity (
    user_id INTEGER PRIMARY KEY REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED,
    last_seen TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_path VARCHAR(255) NOT NULL DEFAULT '/' CHECK (TRIM(last_path) <> ''),
    last_ip INET
);
CREATE INDEX idx_user_activity_last_seen ON user_activity (last_seen);
CREATE INDEX idx_user_activity_last_path ON user_activity (last_path);
CREATE INDEX idx_user_activity_last_ip ON user_activity (last_ip);
CREATE INDEX idx_user_activity_seen_ip ON user_activity (last_seen, last_ip);
CREATE INDEX idx_user_activity_last_seen_active ON user_activity (last_seen DESC) WHERE user_id IS NOT NULL;

CREATE TABLE user_location (
    user_id INTEGER PRIMARY KEY REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED,
    latitude DOUBLE PRECISION NOT NULL CHECK (latitude BETWEEN -90 AND 90),
    longitude DOUBLE PRECISION NOT NULL CHECK (longitude BETWEEN -180 AND 180),
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_user_location_timestamp ON user_location (timestamp);
CREATE INDEX idx_user_location_coordinates ON user_location (latitude, longitude);
CREATE INDEX idx_user_location_geom ON user_location
    USING GIST (ST_SetSRID(ST_MakePoint(longitude, latitude), 4326));
CREATE INDEX idx_user_location_timestamp_active ON user_location (timestamp DESC) WHERE user_id IS NOT NULL;
CREATE INDEX idx_user_location_geom_time ON user_location USING GIST (ST_SetSRID(ST_MakePoint(longitude, latitude), 4326), timestamp DESC);


-- CACHE RELATED TABLES ====================================================================================
CREATE TABLE combain_cache (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    radio_type VARCHAR(10) NOT NULL CHECK (radio_type IN ('GSM', 'UMTS', 'LTE', 'NR', 'CDMA')),
    mcc INTEGER NOT NULL CHECK (mcc BETWEEN 100 AND 999),
    mnc INTEGER NOT NULL CHECK (mnc BETWEEN 0 AND 999),
    lac INTEGER,
    cid INTEGER NOT NULL CHECK (cid >= 0),
    response JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    hits INTEGER NOT NULL DEFAULT 0 CHECK (hits >= 0)
);
CREATE INDEX idx_combain_cache_created_at ON combain_cache (created_at);
CREATE INDEX idx_combain_cache_updated_at ON combain_cache (updated_at);
CREATE INDEX idx_combain_cache_radio_type ON combain_cache (radio_type, mcc, mnc, lac, cid);
CREATE INDEX idx_combain_cache_hits ON combain_cache (hits);
CREATE UNIQUE INDEX uniq_combain_cache_with_lac ON combain_cache (radio_type, mcc, mnc, lac, cid)
    WHERE lac IS NOT NULL;
CREATE UNIQUE INDEX uniq_combain_cache_without_lac ON combain_cache (radio_type, mcc, mnc, cid)
    WHERE lac IS NULL;
CREATE INDEX idx_combain_cache_response ON combain_cache USING GIN (response);

CREATE TABLE google_geolocation_cache (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    radio_type VARCHAR(10) NOT NULL CHECK (radio_type IN ('GSM', 'UMTS', 'LTE', 'NR', 'CDMA')),
    mcc INTEGER NOT NULL CHECK (mcc BETWEEN 100 AND 999),
    mnc INTEGER NOT NULL CHECK (mnc BETWEEN 0 AND 999),
    lac INTEGER,
    cid INTEGER NOT NULL CHECK (cid >= 0),
    response JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    hits INTEGER NOT NULL DEFAULT 0 CHECK (hits >= 0)
);
CREATE INDEX idx_google_geo_cache_created_at ON google_geolocation_cache (created_at);
CREATE INDEX idx_google_geo_cache_updated_at ON google_geolocation_cache (updated_at);
CREATE INDEX idx_google_geo_cache_radio_type ON google_geolocation_cache (radio_type, mcc, mnc, lac, cid);
CREATE INDEX idx_google_geo_cache_hits ON google_geolocation_cache (hits);
CREATE UNIQUE INDEX uniq_google_geocache_with_lac ON google_geolocation_cache (radio_type, mcc, mnc, lac, cid)
    WHERE lac IS NOT NULL;
CREATE UNIQUE INDEX uniq_google_geocache_without_lac ON google_geolocation_cache (radio_type, mcc, mnc, cid)
    WHERE lac IS NULL;
CREATE INDEX idx_google_geocache_response ON google_geolocation_cache USING GIN (response);

-- SPECIFIC SEARCHES TABLES =================================================================================
CREATE TABLE chronological_path_analysis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_filename VARCHAR(255) NOT NULL CHECK (TRIM(original_filename) <> ''),
    parameters JSONB NOT NULL CHECK (jsonb_typeof(parameters) = 'object' AND jsonb_array_length(parameters) > 0),
    summary JSONB NOT NULL CHECK (jsonb_typeof(summary) = 'object' AND jsonb_array_length(summary) > 0),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id INTEGER NOT NULL REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX idx_chronological_path_analysis_user_id ON chronological_path_analysis (user_id);
CREATE INDEX idx_chronological_path_analysis_created_at ON chronological_path_analysis (created_at);
CREATE INDEX idx_chronological_path_analysis_updated_at ON chronological_path_analysis (updated_at);
CREATE INDEX idx_chronological_path_analysis_filename ON chronological_path_analysis (original_filename);
CREATE INDEX idx_chronological_path_analysis_parameters ON chronological_path_analysis USING GIN (parameters);
CREATE INDEX idx_chronological_path_analysis_summary ON chronological_path_analysis USING GIN (summary);
CREATE INDEX idx_chronological_path_analysis_user_created ON chronological_path_analysis (user_id, created_at DESC);

-- FUNCTIONS AND TRIGGERS =======================================================================================
-- Function to update last_seen
CREATE OR REPLACE FUNCTION update_user_activity()
    RETURNS TRIGGER AS $$
BEGIN
    UPDATE user_activity
    SET
        last_seen = CURRENT_TIMESTAMP,
        last_path = NEW.last_path,
        last_ip = NEW.last_ip
    WHERE user_id = NEW.user_id;

    -- If not found, insert
    IF NOT FOUND THEN
        INSERT INTO user_activity (user_id, last_seen, last_path, last_ip)
        VALUES (NEW.user_id, CURRENT_TIMESTAMP, NEW.last_path, NEW.last_ip);
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Function to update user timestamp
CREATE OR REPLACE FUNCTION update_user_location_timestamp()
    RETURNS TRIGGER AS $$
BEGIN
    NEW.timestamp = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger
CREATE TRIGGER update_user_location_timestamp
    BEFORE UPDATE ON user_location
    FOR EACH ROW
EXECUTE FUNCTION update_user_location_timestamp();

-- Function to update updated_at in combain cache
CREATE OR REPLACE FUNCTION update_combain_cache_updated_at()
    RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger
CREATE TRIGGER update_combain_cache_updated_at
    BEFORE UPDATE ON combain_cache
    FOR EACH ROW
EXECUTE FUNCTION update_combain_cache_updated_at();

-- Function to update updated_at Google geocache
CREATE OR REPLACE FUNCTION update_google_geocache_updated_at()
    RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger
CREATE TRIGGER update_google_geocache_updated_at
    BEFORE UPDATE ON google_geolocation_cache
    FOR EACH ROW
EXECUTE FUNCTION update_google_geocache_updated_at();

-- Function to update chronological analysis updated_at
CREATE OR REPLACE FUNCTION update_chronological_path_analysis_updated_at()
    RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger
CREATE TRIGGER update_chronological_path_analysis_updated_at
    BEFORE UPDATE ON chronological_path_analysis
    FOR EACH ROW
EXECUTE FUNCTION update_chronological_path_analysis_updated_at();

-- Trigger para atualizar updated_at cell table
CREATE OR REPLACE FUNCTION update_cell_updated_at()
    RETURNS TRIGGER AS $$
BEGIN
    IF NEW.updated_at IS NOT DISTINCT FROM OLD.updated_at THEN
        NEW.updated_at = CURRENT_TIMESTAMP;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_cell_updated_at
    BEFORE UPDATE ON cell
    FOR EACH ROW
EXECUTE FUNCTION update_cell_updated_at();