spring.application.name=geocell

# PostgreSQL Configurations
spring.datasource.url=${DB_URL:jdbc:postgresql://192.168.1.95:5432/geocell}
spring.datasource.username=${DB_USERNAME:geocell_user}
spring.datasource.password=${DB_PASSWORD:4w5_Yd4xee35$}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Additional Configurations
spring.jpa.open-in-view=false

# Multipart upload limits
spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=30MB